import type {
  MatchMode,
  PuzzleCatalogEntry,
  PuzzleDifficulty,
} from "@alchemizt/contracts";

type CatalogSeed = {
  readonly id: string;
  readonly title: string;
  readonly targetMolecule: string;
  readonly difficulty: PuzzleDifficulty;
  readonly estimatedSeconds: number;
  readonly referenceSteps: number;
  readonly referenceCost: number;
  readonly topicTags: string[];
  readonly theme: string;
  readonly allowedReactions: string[];
  readonly restrictedReagents?: string[];
  readonly modeAvailability: MatchMode[];
  readonly commonPitfalls: string[];
  readonly description?: string;
  readonly countdownSeconds: number;
  readonly totalSeconds: number;
};

const createEntry = (seed: CatalogSeed): PuzzleCatalogEntry => ({
  metadata: {
    id: seed.id,
    title: seed.title,
    targetMolecule: seed.targetMolecule,
    difficulty: seed.difficulty,
    estimatedSeconds: seed.estimatedSeconds,
    referenceSteps: seed.referenceSteps,
    referenceCost: seed.referenceCost,
    topicTags: seed.topicTags,
    theme: seed.theme,
    allowedReactions: seed.allowedReactions,
    restrictedReagents: seed.restrictedReagents,
    modeAvailability: seed.modeAvailability,
    commonPitfalls: seed.commonPitfalls,
    description: seed.description,
  },
  timerPreset: {
    countdownSeconds: seed.countdownSeconds,
    totalSeconds: seed.totalSeconds,
  },
});

const SOLO_MODES: MatchMode[] = ["speedrun"];
const DUEL_MODES: MatchMode[] = ["speedrun", "endurance"];

export const PUZZLE_CATALOG: PuzzleCatalogEntry[] = [
  createEntry({
    id: "pz-carbonyl-01",
    title: "Acetophenone Sprint",
    targetMolecule: "C8H8O",
    difficulty: "practice",
    estimatedSeconds: 360,
    referenceSteps: 4,
    referenceCost: 12,
    topicTags: ["ketone", "friedel-crafts", "acylation"],
    theme: "Carbonyl Foundations",
    allowedReactions: ["Friedel-Crafts acylation", "Oxidation"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Over-acylation on polysubstituted ring"],
    description: "Build acetophenone from toluene with a single acylation window.",
    countdownSeconds: 5,
    totalSeconds: 600,
  }),
  createEntry({
    id: "pz-carbonyl-02",
    title: "Lactone Relay",
    targetMolecule: "C6H8O3",
    difficulty: "practice",
    estimatedSeconds: 420,
    referenceSteps: 5,
    referenceCost: 15,
    topicTags: ["lactone", "oxidation", "ring-closing"],
    theme: "Carbonyl Week",
    allowedReactions: ["Baeyer-Villiger", "Esterification"],
    restrictedReagents: ["concentrated H2SO4"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Incorrect migrating group during Baeyer-Villiger"],
    countdownSeconds: 5,
    totalSeconds: 660,
  }),
  createEntry({
    id: "pz-carbonyl-03",
    title: "Aldol Mirror Match",
    targetMolecule: "C10H12O2",
    difficulty: "advanced",
    estimatedSeconds: 540,
    referenceSteps: 6,
    referenceCost: 18,
    topicTags: ["aldol", "stereochemistry"],
    theme: "Aldol Arena",
    allowedReactions: ["Aldol condensation", "Hydrogenation"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Failing to control enolate geometry"],
    countdownSeconds: 5,
    totalSeconds: 720,
  }),
  createEntry({
    id: "pz-carbonyl-04",
    title: "Diels-Alder Carbonyl Bridge",
    targetMolecule: "C12H14O3",
    difficulty: "advanced",
    estimatedSeconds: 600,
    referenceSteps: 7,
    referenceCost: 22,
    topicTags: ["diels-alder", "anhydride"],
    theme: "Cycloaddition Spotlight",
    allowedReactions: ["Diels-Alder", "Anhydride hydrolysis"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Misaligned diene orientation"],
    countdownSeconds: 5,
    totalSeconds: 780,
  }),
  createEntry({
    id: "pz-carbonyl-05",
    title: "Claisen Chorus",
    targetMolecule: "C11H14O3",
    difficulty: "advanced",
    estimatedSeconds: 570,
    referenceSteps: 6,
    referenceCost: 21,
    topicTags: ["claisen", "beta-keto ester"],
    theme: "Enolate Month",
    allowedReactions: ["Claisen condensation", "Decarboxylation"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Using insufficiently strong base for Claisen"],
    countdownSeconds: 5,
    totalSeconds: 750,
  }),
  createEntry({
    id: "pz-carbonyl-06",
    title: "Wittig Warmup",
    targetMolecule: "C10H12O",
    difficulty: "practice",
    estimatedSeconds: 330,
    referenceSteps: 4,
    referenceCost: 14,
    topicTags: ["wittig", "alkene"],
    theme: "Carbonyl Week",
    allowedReactions: ["Wittig olefination", "Oxidation"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Selecting the wrong phosphonium ylide"],
    countdownSeconds: 5,
    totalSeconds: 540,
  }),
  createEntry({
    id: "pz-carbonyl-07",
    title: "Baeyer Beat",
    targetMolecule: "C9H10O3",
    difficulty: "practice",
    estimatedSeconds: 390,
    referenceSteps: 5,
    referenceCost: 16,
    topicTags: ["baeyer-villiger", "ketone"],
    theme: "Oxidation Sprint",
    allowedReactions: ["Baeyer-Villiger", "Reduction"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Forgetting to protect phenolic ring before oxidation"],
    countdownSeconds: 5,
    totalSeconds: 630,
  }),
  createEntry({
    id: "pz-carbonyl-08",
    title: "Oxime Pivot",
    targetMolecule: "C7H9NO",
    difficulty: "practice",
    estimatedSeconds: 360,
    referenceSteps: 4,
    referenceCost: 12,
    topicTags: ["oxime", "ketone", "reduction"],
    theme: "Nitrogen Adjunct",
    allowedReactions: ["Oxime formation", "Reduction"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Over-reduction yielding amine"],
    countdownSeconds: 5,
    totalSeconds: 600,
  }),
  createEntry({
    id: "pz-carbonyl-09",
    title: "Amide Ladder",
    targetMolecule: "C11H15NO2",
    difficulty: "advanced",
    estimatedSeconds: 540,
    referenceSteps: 6,
    referenceCost: 20,
    topicTags: ["amide coupling", "protecting groups"],
    theme: "Peptide Prep",
    allowedReactions: ["Amide coupling", "Boc protection"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Failing to deprotect before final coupling"],
    countdownSeconds: 5,
    totalSeconds: 780,
  }),
  createEntry({
    id: "pz-carbonyl-10",
    title: "Keto-Enol Gauntlet",
    targetMolecule: "C9H10O2",
    difficulty: "contest",
    estimatedSeconds: 660,
    referenceSteps: 7,
    referenceCost: 24,
    topicTags: ["tautomerization", "aldol"],
    theme: "Contest Ladder",
    allowedReactions: ["Aldol addition", "Tautomerization control"],
    restrictedReagents: ["LDA"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Wrong enolate order causing scrambling"],
    countdownSeconds: 5,
    totalSeconds: 840,
  }),
  createEntry({
    id: "pz-aromatic-01",
    title: "Benzofuran Bloom",
    targetMolecule: "C8H6O",
    difficulty: "practice",
    estimatedSeconds: 390,
    referenceSteps: 4,
    referenceCost: 13,
    topicTags: ["benzofuran", "cyclization"],
    theme: "Aromatic Foundations",
    allowedReactions: ["Fischer synthesis", "Cyclodehydration"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Overheating during cyclization"],
    countdownSeconds: 5,
    totalSeconds: 600,
  }),
  createEntry({
    id: "pz-aromatic-02",
    title: "Suzuki Showcase",
    targetMolecule: "C13H10O",
    difficulty: "advanced",
    estimatedSeconds: 540,
    referenceSteps: 5,
    referenceCost: 19,
    topicTags: ["suzuki", "biaryl"],
    theme: "Cross-Coupling Month",
    allowedReactions: ["Suzuki coupling", "Bromination"],
    restrictedReagents: ["Pd/C recycling"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Incorrect boronic acid partner order"],
    countdownSeconds: 5,
    totalSeconds: 780,
  }),
  createEntry({
    id: "pz-aromatic-03",
    title: "Sandmeyer Switch",
    targetMolecule: "C6H4ClNO2",
    difficulty: "practice",
    estimatedSeconds: 420,
    referenceSteps: 4,
    referenceCost: 14,
    topicTags: ["sandmeyer", "diazonium"],
    theme: "Aromatic Substitution Month",
    allowedReactions: ["Diazotization", "Sandmeyer substitution"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Failing to keep diazonium salt cold"],
    countdownSeconds: 5,
    totalSeconds: 660,
  }),
  createEntry({
    id: "pz-aromatic-04",
    title: "Electrophilic Edge",
    targetMolecule: "C7H6O2",
    difficulty: "practice",
    estimatedSeconds: 360,
    referenceSteps: 4,
    referenceCost: 12,
    topicTags: ["acylation", "aromatic"],
    theme: "Carbonyl Week",
    allowedReactions: ["Friedel-Crafts acylation", "Hydrolysis"],
    modeAvailability: SOLO_MODES,
    commonPitfalls: ["Blocking group not removed"],
    countdownSeconds: 5,
    totalSeconds: 600,
  }),
  createEntry({
    id: "pz-aromatic-05",
    title: "Nitration Matrix",
    targetMolecule: "C6H4(NO2)2",
    difficulty: "advanced",
    estimatedSeconds: 480,
    referenceSteps: 4,
    referenceCost: 16,
    topicTags: ["nitration", "dir-substitution"],
    theme: "Aromatic Substitution Month",
    allowedReactions: ["Mononitration", "Dinitration"],
    restrictedReagents: ["fuming nitric acid"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Meta vs para confusion"],
    countdownSeconds: 5,
    totalSeconds: 720,
  }),
  createEntry({
    id: "pz-aromatic-06",
    title: "Phenol Cascade",
    targetMolecule: "C10H8O3",
    difficulty: "advanced",
    estimatedSeconds: 510,
    referenceSteps: 5,
    referenceCost: 18,
    topicTags: ["phenol", "electrophilic substitution"],
    theme: "Aromatic Foundations",
    allowedReactions: ["Kolbe-Schmitt", "Sulfonation"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["CO2 pressure mismanagement"],
    countdownSeconds: 5,
    totalSeconds: 750,
  }),
  createEntry({
    id: "pz-aromatic-07",
    title: "Indole Inversion",
    targetMolecule: "C8H7N",
    difficulty: "advanced",
    estimatedSeconds: 540,
    referenceSteps: 6,
    referenceCost: 20,
    topicTags: ["indole", "Fischer"],
    theme: "Heterocycle Sprint",
    allowedReactions: ["Fischer indole synthesis", "Reductive workup"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Protonating hydrazone prematurely"],
    countdownSeconds: 5,
    totalSeconds: 780,
  }),
  createEntry({
    id: "pz-aromatic-08",
    title: "Azo Canvas",
    targetMolecule: "C12H10N2O3",
    difficulty: "contest",
    estimatedSeconds: 660,
    referenceSteps: 7,
    referenceCost: 24,
    topicTags: ["azo dye", "diazotization"],
    theme: "Colorant Contest",
    allowedReactions: ["Diazotization", "Azo coupling"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["pH drift causing azo failure"],
    countdownSeconds: 5,
    totalSeconds: 900,
  }),
  createEntry({
    id: "pz-aromatic-09",
    title: "Polyaryl Ladder",
    targetMolecule: "C18H14",
    difficulty: "contest",
    estimatedSeconds: 720,
    referenceSteps: 8,
    referenceCost: 28,
    topicTags: ["polyaryl", "cross-coupling"],
    theme: "Seasonal Contest",
    allowedReactions: ["Suzuki", "Heck"],
    restrictedReagents: ["Ni catalysts"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Skipping oxidative addition prep"],
    countdownSeconds: 5,
    totalSeconds: 960,
  }),
  createEntry({
    id: "pz-aromatic-10",
    title: "Cross-Coupling Clash",
    targetMolecule: "C15H13BrO",
    difficulty: "contest",
    estimatedSeconds: 690,
    referenceSteps: 7,
    referenceCost: 26,
    topicTags: ["cross coupling", "halogen shuffle"],
    theme: "Contest Ladder",
    allowedReactions: ["Suzuki", "Halogen dance"],
    modeAvailability: DUEL_MODES,
    commonPitfalls: ["Losing bromide handle early"],
    countdownSeconds: 5,
    totalSeconds: 930,
  }),
];

const catalogMap = new Map(PUZZLE_CATALOG.map((entry) => [entry.metadata.id, entry]));

export const listPuzzles = (): PuzzleCatalogEntry[] => PUZZLE_CATALOG;

export const getPuzzleById = (puzzleId: string): PuzzleCatalogEntry | undefined =>
  catalogMap.get(puzzleId);

